### ISSUE TITLE
Requesting Hyprland dots

### ISSUE THREAD

**Issue by DieALot36T9** [DoubleDotStudios/dotfiles#2]
Is you laptop a 15ada05? If so can I would like to have a look at your Hypr dots.

**Comment by vaelixd** [comment]
My dot files for hyprland can be found [here](https://github.com/prasanthrangan/hyprdots/tree/main/Configs/.config/hyde) and [here](https://github.com/prasanthrangan/hyprdots/tree/main/Configs/.config/hypr). I haven’t got round to doing much ricing. I’ve changed a few keyboard shortcuts but nothing major. 

If I make any major changes then I’ll upload the dots here but for now they’re pretty much the same as the preconfigured ones.
